name: Bug
description: Report a bug in the system
title: "[Bug]: <title>"
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps the reproduce the behavior.
      placeholder: |
        1. Setup ...
        2. Call function ...
        3. See exception ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **NET version**: .NET 9
          - **OS**: Windows 11
          - **Version**: v1.0.1
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
