name: Documentation
description: Suggest updates or additions to documentation
title: "[Docs]: <title>"
labels: docs
body:
  - type: textarea
    attributes:
      label: Documentation update
      description: What part of the documentation needs to be updated or added?
      validations:
        required: true
  - type: textarea
    attributes:
      label: Why is this needed?
      description: Explain the importance of this update.
      validations:
        required: true
  - type: textarea
    attributes:
      label: Suggested changes
      description: Provide a detailed description of the changes.
      validations:
        required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      validations:
        required: false
